<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Ingest Result</title>
        <link rel="stylesheet" href="https://unpkg.com/purecss@0.6.2/build/pure-min.css" integrity="sha384-UQiGfs9ICog+LwheBSRCt1o5cbyKIHbwjWscjemyBMT9YCUMZffs6UqUTd0hObXD" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div class="content">
	        <div class="pure-g">
	            <div class="pure-u-1">
	                <h1>Ingest Result</h1>
	            </div>
                <?php
                foreach ($result as $res) {
                ?>
                <div class="pure-u-1">
                    <h2><?= $res ?></h2>
                </div>
                <?php
                }
                ?>
            </div>
        </div>
    </body>
</html>